### ISSUE TITLE
Make methods that request data lazy

### ISSUE THREAD

**Issue by micha-f** [Contiamo/rest-client#9]
As per @peterszerzo 's recommendation. Really nice idea.

**Comment by micha-f** [comment]
How would we go about doing this? Maybe we can start with the fetch method: https://github.com/Contiamo/rest-client/blob/master/src/capabilities/resource.ts#L10

Making mutating requests lazy does not make sense, so we can ignore those.

**Comment by TejasQ** [comment]
@micha-f, it would be nice if you put context or the conversation into the first comment of this issue for clarity.

**Comment by micha-f** [comment]
We agreed that this could be a nice exercise but doesn't really add any value at this point.
